name: Web Server CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  deploy:
    name: Deploy to shinyapps

    # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
    if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Swith to online version
        run: |
        
          # Modify server.R
          sed -i  '1s/.*/online = TRUE/' server.R
          
          # Minimize examplefile
          echo 'Please refer to the local version for viewing.' > examplefile/root/mascot/mascot_xml/Exp027017/Exp027017_F1_R1.txt
          echo 'Please refer to the local version for viewing.' > examplefile/root/mascot/mascot_xml/Exp027031/Exp027031_F1_R1.txt
          echo 'Please refer to the local version for viewing.' > examplefile/root/mascot/mascot_xml/Exp027032/Exp027032_F1_R1.txt
          echo 'Please refer to the local version for viewing.' > examplefile/root/mascot/mascot_xml/Exp027033/Exp027033_F1_R1.txt
          echo 'Please refer to the local version for viewing.' > examplefile/root/mascot/mascot_xml/Exp027046/Exp027046_F1_R1.txt
          echo 'Please refer to the local version for viewing.' > examplefile/root/mascot/mascot_xml/Exp027047/Exp027047_F1_R1.txt
          echo 'Please refer to the local version for viewing.' > examplefile/root/mascot/mascot_xml/Exp027048/Exp027048_F1_R1.txt
          
          # Get phosmap_online_data
          git clone https://github.com/liuzan-info/phosmap_online_data.git
          mv phosmap_online_data PhosMap_datasets
      - 
        name: Deploy
        uses: liuzan-info/shinyapps-deploy-github-action@v1.0.2
        with:
          # account and application name (https://<accountName>.shinyapps.io/<appName>)
          appName: PhosMap
          accountName: bio-inf

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
